### ISSUE TITLE
No release?

### ISSUE THREAD

**Issue by hasufell** [i-am-tom/oops#2]
Is this not usable already?

**Comment by i-am-tom** [comment]
It is definitely usable! I'm not sure why I never got around to releasing it, but @parsonsmatt has since released [plucky](https://hackage.haskell.org/package/plucky-0.0.0.1/docs/Data-Either-Plucky.html), which I think achieves the same thing in practice.

This repo is still here just because I think it's a very neat approach to the problem, but I think Plucky works great, and I didn't want to unnecessarily confuse a new user browsing Hackage! If you think it has independent merit, though, I'd be willing to put a release together - I've not looked at this package in a long time, and I'm now leaning more towards building a more general-purpose library of hlists, variants, etc, which would probably encompass this entire API.

**Comment by newhoggy** [comment]
@hasufell what approach did you end up using?

**Comment by hasufell** [comment]
> @hasufell what approach did you end up using?

- https://docs.haskus.org/variant/excepts.html
- https://hackage.haskell.org/package/haskus-utils-variant-3.3/docs/Haskus-Utils-Variant-Excepts.html
