### ISSUE TITLE
Comparison to other open variant solutions

### ISSUE THREAD

**Issue by hasufell** [i-am-tom/oops#3]
I'm mainly interested on how this compares to haskus Excepts:

* https://docs.haskus.org/variant/excepts.html
* https://hackage.haskell.org/package/haskus-utils-variant-3.0/docs/Haskus-Utils-Variant-Excepts.html

**Comment by i-am-tom** [comment]
Just from a quick look, I would guess that using concrete error lists (e.g. `'[This, That, Them]`) over constraints (e.g. `(HasError This e, HasError That e, HasError Them e) => e`) means your errors are necessarily ordered? I don't know this library at all, though, so I wouldn't necessarily trust myself.

From a skim read, it would seem closer to the approach I took the first time I tried to build a variant: https://github.com/i-am-tom/learn-me-a-haskell#oneof

This is fine, but it becomes annoying when GHC can't unify `Variant '[Int, Bool]` with `Variant '[Bool, Int]`, for example, and a constraint-based approach would side-step this problem (because constraints aren't ordered).

**Comment by hasufell** [comment]
> This is fine, but it becomes annoying when GHC can't unify Variant '[Int, Bool] with Variant '[Bool, Int], for example, and a constraint-based approach would side-step this problem (because constraints aren't ordered).

It unifies via [liftE](https://hackage.haskell.org/package/haskus-utils-variant-3.0/docs/Haskus-Utils-Variant-Excepts.html#v:liftE). I'm using that approach right now in [ghcup](https://gitlab.haskell.org/haskell/ghcup-hs/-/blob/master/lib/GHCup.hs#L88), but it is not that ergonomic and I need to heavily use type applications in some places and liftE all over the place. And the biggest problem is that you never know whether you have extraneous constraints. With classes, that can get a little better, but the unnecessary constraints solver is only best effort anyway and quickly breaks down with type families.

I've never used plucky. Do you think that is preferable over oops?

**Comment by i-am-tom** [comment]
I spoke with @parsonsmatt, and he seems to think Plucky will suit your needs! Honestly, it's not a library I've used in anger, but I've heard good things from colleagues, and Matt's work is reliably wonderful. Plucky is certainly more likely to be maintained than this library ever will be; as I say, this will probably disappear (when I have some motivation to write some code again) in favour of a bigger library of strongly-typed utilities.
